thisdir = tools/btls
SUBDIRS = 
include ../../build/rules.make

LOCAL_MCS_FLAGS =
LIB_REFS = System Mono.Security Mono.Security.Providers.Btls
PROGRAM = btls-cert-sync.exe

include ../../build/executable.make
